webtalk_init -webtalk_dir C:/Users/campbellrobert/Desktop/final/test2/test2.sim/sim_1/behav/xsim/xsim.dir/i2c_master_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec  3 14:28:43 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174119796_174119797_210705425_148" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a031f6ff-5af9-4ba6-a4d8-1bb41df3cd3f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b9982891ab9840abad6d799c48e0a4cf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3696 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "137.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.45_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14936_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1642262641 -regid "174119796_174119797_210705425_148" -xml C:/Users/campbellrobert/Desktop/final/test2/test2.sim/sim_1/behav/xsim/xsim.dir/i2c_master_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/campbellrobert/Desktop/final/test2/test2.sim/sim_1/behav/xsim/xsim.dir/i2c_master_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/campbellrobert/Desktop/final/test2/test2.sim/sim_1/behav/xsim/xsim.dir/i2c_master_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
