@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sun Nov 29 16:52:53 -0600 2020
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto a9f225719dbf4802a31c3ea06b8c2a1c --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot wordtest_behav xil_defaultlib.wordtest -log elaborate.log"
call xelab  -wto a9f225719dbf4802a31c3ea06b8c2a1c --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot wordtest_behav xil_defaultlib.wordtest -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
